# Generated by Django 3.0.4 on 2020-03-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alabooking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reason',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
