# Generated by Django 3.0.4 on 2020-03-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alabooking', '0002_booking_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='dateToBeUsed',
            field=models.DateField(null=True),
        ),
    ]
